name: flutter_application_1
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  intl:
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  assets:
    - assets/
    - assets/bikes/
  uses-material-design: true

  fonts:
    - family: "Neue"
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
